% EXAMPLE USAGE FOR PGRID AND PMERGE
h   = figure; 
[phandle, pidx] = pgrid(3, 4,     ...
  'parent',         h,            ...
  'relwidth',       [1 2 3 3],    ...
  'relheight',      [.25 1 .25],  ...
  'panelsep',       .005,         ...
  'marginsep',      .001,         ...
  'backg',          [0 0 0],      ...
  'foreg',          [1 1 1],      ...
  'bordertype',     'none',       ...
  'borderwidth',    2             ...
);
mhgrid1 = pmerge(phandle, 1:3);
mhgrid2 = pmerge(mhgrid1, 7:9);
shpanel = psplit(mhgrid2, 2, 1, .005);
